spring.application.name=parking_spot_finder

spring.datasource.url=jdbc:mysql://localhost:3306/parking_spot_finder
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8080
